project:
  type: website

website:
  title: "SGY ADTA"
  navbar:
    right:
        - text: "Home"
          href: index.qmd
        - text: "Resume"
          href: Resume.qmd
        - text: "Blog"
          href: blog.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

